import { NextResponse } from 'next/server';
import { requireAdmin } from '@/lib/auth';
import dbConnect from '@/lib/mongodb';
import NewsArticle from '@/models/NewsArticle';
import { sanitizeRichText } from '@/lib/sanitize';

export const dynamic = 'force-dynamic';

// GET — Admin sees all articles (drafts + published)
export async function GET() {
  const { session, error } = await requireAdmin();
  if (error) return error;

  try {
    await dbConnect();
    const articles = await NewsArticle.find({}).sort({ createdAt: -1 }).lean();
    return NextResponse.json(articles);
  } catch (error) {
    return NextResponse.json({ error: 'Failed to fetch articles.' }, { status: 500 });
  }
}

// POST — Create new article (slug is auto-generated by model pre-save hook)
export async function POST(request) {
  const { session, error } = await requireAdmin();
  if (error) return error;

  try {
    await dbConnect();
    const body = await request.json();
    if (body.content) body.content = sanitizeRichText(body.content);
    // Slug and publishedAt are handled by the pre-save hook in the model
    const article = await NewsArticle.create(body);
    return NextResponse.json(article, { status: 201 });
  } catch (error) {
    return NextResponse.json({ error: error.message }, { status: 400 });
  }
}

// PUT — Update article
export async function PUT(request) {
  const { session, error } = await requireAdmin();
  if (error) return error;

  try {
    await dbConnect();
    const { _id, ...updateData } = await request.json();
    if (updateData.content) updateData.content = sanitizeRichText(updateData.content);

    // Set publishedAt on first publish only (findByIdAndUpdate bypasses the
    // pre-save hook). Check the EXISTING document, not the request body — the
    // edit form never sends publishedAt back, so it's always absent from the
    // body and checking that would re-stamp it to "now" on every save.
    if (updateData.isPublished && !updateData.publishedAt) {
      const existing = await NewsArticle.findById(_id).select('publishedAt').lean();
      if (existing && !existing.publishedAt) {
        updateData.publishedAt = new Date();
      }
    }

    const article = await NewsArticle.findByIdAndUpdate(_id, updateData, {
      new: true,
      runValidators: true,
    });

    if (!article) return NextResponse.json({ error: 'Article not found.' }, { status: 404 });
    return NextResponse.json(article);
  } catch (error) {
    return NextResponse.json({ error: error.message }, { status: 400 });
  }
}


// DELETE — Delete article
export async function DELETE(request) {
  const { session, error } = await requireAdmin();
  if (error) return error;

  try {
    await dbConnect();
    const { searchParams } = new URL(request.url);
    const id = searchParams.get('id');
    const article = await NewsArticle.findByIdAndDelete(id);
    if (!article) return NextResponse.json({ error: 'Article not found.' }, { status: 404 });
    return NextResponse.json({ success: true });
  } catch (error) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
