import { NextResponse } from 'next/server';
import { getServerSession } from 'next-auth/next';
import { authOptions } from '@/app/api/auth/[...nextauth]/route';
import dbConnect from '@/lib/mongodb';
import NewsArticle from '@/models/NewsArticle';

export const dynamic = 'force-dynamic';

// GET — Admin sees all articles (drafts + published)
export async function GET() {
  const session = await getServerSession(authOptions);
  if (!session) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

  try {
    await dbConnect();
    const articles = await NewsArticle.find({}).sort({ createdAt: -1 }).lean();
    return NextResponse.json(articles);
  } catch (error) {
    return NextResponse.json({ error: 'Failed to fetch articles.' }, { status: 500 });
  }
}

// POST — Create new article (slug is auto-generated by model pre-save hook)
export async function POST(request) {
  const session = await getServerSession(authOptions);
  if (!session) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

  try {
    await dbConnect();
    const body = await request.json();
    // Slug and publishedAt are handled by the pre-save hook in the model
    const article = await NewsArticle.create(body);
    return NextResponse.json(article, { status: 201 });
  } catch (error) {
    return NextResponse.json({ error: error.message }, { status: 400 });
  }
}

// PUT — Update article
export async function PUT(request) {
  const session = await getServerSession(authOptions);
  if (!session) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

  try {
    await dbConnect();
    const { _id, ...updateData } = await request.json();

    // Set publishedAt on first publish (findByIdAndUpdate bypasses pre-save hook)
    if (updateData.isPublished && !updateData.publishedAt) {
      updateData.publishedAt = new Date();
    }

    const article = await NewsArticle.findByIdAndUpdate(_id, updateData, {
      new: true,
      runValidators: true,
    });

    if (!article) return NextResponse.json({ error: 'Article not found.' }, { status: 404 });
    return NextResponse.json(article);
  } catch (error) {
    return NextResponse.json({ error: error.message }, { status: 400 });
  }
}


// DELETE — Delete article
export async function DELETE(request) {
  const session = await getServerSession(authOptions);
  if (!session) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

  try {
    await dbConnect();
    const { searchParams } = new URL(request.url);
    const id = searchParams.get('id');
    const article = await NewsArticle.findByIdAndDelete(id);
    if (!article) return NextResponse.json({ error: 'Article not found.' }, { status: 404 });
    return NextResponse.json({ success: true });
  } catch (error) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
