import mongoose from 'mongoose';

const GalleryImageSchema = new mongoose.Schema(
  {
    caption: {
      type: String,
      required: true,
      trim: true,
    },
    // Cloudinary public ID for deletion/transformation
    publicId: {
      type: String,
      default: '',
    },
    // Full Cloudinary URL or external URL
    imageUrl: {
      type: String,
      required: true,
    },
    // Optimized thumbnail URL (generated by Cloudinary)
    thumbnailUrl: {
      type: String,
      default: '',
    },
    // Category for filtering on the gallery page
    category: {
      type: String,
      enum: ['All', 'Wildlife', 'Community', 'Events', 'Environment', 'Other'],
      default: 'All',
    },
    order: {
      type: Number,
      default: 0,
    },
    isVisible: {
      type: Boolean,
      default: true,
    },
  },
  { timestamps: true }
);

export default mongoose.models.GalleryImage ||
  mongoose.model('GalleryImage', GalleryImageSchema);
